### PR TITLE
Rebrand as @zazuko package

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by tpluscode** [comment]
Sorry, this was meant as PR in the fork itself.

**Comment by bergos** [comment]
@tpluscode I recommend restoring my credits. If you forked any of my other packages, I suggest you also do it there.

**Comment by tpluscode** [comment]
Fair enough

**Comment by danja** [comment]
I'd strongly recommend against moves like this. Ok, it might not make any difference in licensing or practical terms. But from the outside it gives the impression of a company taking open source and calling it their own. Not a good image to project.
Personally I'd try to avoid software where branding becomes a (GitHub) issue. I don't know all the details of this lib in particular, but leaving original credits in place, adding to them as appropriate seems a more decent approach.

**Pull request closed without merging**
